# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ITWORX.CtrlVTerminal
PackageVersion: 1.2.5
InstallerType: nullsoft
Scope: machine
ElevationRequirement: elevatesSelf
UpgradeBehavior: install
ReleaseDate: 2026-09-11
InstallationMetadata:
  DefaultInstallLocation: "%ProgramFiles%\\Ctrl-V Terminal"
AppsAndFeaturesEntries:
- DisplayName: Ctrl-V Terminal 1.2.5
  DisplayVersion: 1.2.5
  ProductCode: c16cde77-22e1-5568-bdae-e8ff97d9f3ba
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/it-worx-nl/ctrl-v-terminal-releases/releases/download/v1.2.5/Ctrl-V-Terminal-Setup-1.2.5.exe
  InstallerSha256: A993601579EC2255868BDD2653352C59686AFBCDE14350E546AEF40A2026E5FC
ManifestType: installer
ManifestVersion: 1.12.0
